name: Build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 16
        uses: actions/setup-java@v4
        with:
          java-version: 16
          distribution: 'temurin'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: create run dir
        run: |
          mkdir run
      - name: build
        run: ./gradlew build --stacktrace --info
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
          if-no-files-found: error
      - name: capture test results
        uses: test-summary/action@v2
        with:
          paths: build/test-results/**/*.xml
        if: always()
